trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '1.0.11'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-service-connection'  
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az login --service-principal -u $(ARM_CLIENT_ID) -p $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID)'

- script: |
    terraform init
  displayName: 'Terraform Init'

- script: |
    terraform import azurerm_resource_group.example /subscriptions/229dc9f9-5b23-47e2-8853-f099755e0d70/resourceGroups/example-resources || echo "Resource already imported"
  displayName: 'Terraform Import'

- script: |
    terraform plan -out=tfplan
  displayName: 'Terraform Plan'

- script: |
    terraform apply -auto-approve tfplan
  displayName: 'Terraform Apply'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-service-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Get the app service default hostname
      hostname=$(az webapp show --resource-group example-resources --name example-appservice --query defaultHostName -o tsv)
      echo "App Service URL: http://$hostname"
